import { StockDetailClient } from "@/app/stock/[ticker]/stock-detail-client";
import { Header } from "@/components/layout/header";
import { Metadata } from "next";
import { generateStockMetadata, generateEnhancedStockMetadata } from "@/components/seo/stock-seo";

type Params = {
  ticker: string;
};

export default async function StockDetailPage({ params }: { params: Params }) {
  // In Next.js 15, we need to handle params as a promise
  const ticker = (await params).ticker.toUpperCase();
  
  return (
    <div className="min-h-screen flex flex-col bg-[#FDFBF7] dark:bg-[#121110] text-slate-900 dark:text-slate-100 transition-colors">
      <Header />
      <main className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 py-6 sm:py-8 w-full">
        <StockDetailClient ticker={ticker} />
      </main>

      {/* Educational Disclaimer matching ArticleFrame */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 pb-12 w-full">
        <div className="bg-[#A8672E]/5 dark:bg-[#D08F52]/10 border-l-4 border-[#A8672E] dark:border-[#D08F52] p-6 rounded-r-2xl">
          <h4 className="font-serif font-bold text-[#A8672E] dark:text-[#D08F52] mb-1.5">Educational Disclaimer</h4>
          <p className="text-slate-600 dark:text-slate-400 text-xs sm:text-sm leading-relaxed">
            SOPHIE analysis is for educational purposes only, intended for people to learn more about finance, but not giving financial advice. All suggestions and valuations are generated by AI models and quantitative algorithms.
          </p>
        </div>
      </div>

      <footer className="border-t border-gray-200 dark:border-gray-800/80 bg-white/40 dark:bg-gray-900/40 py-8 sm:py-12">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 text-center">
          <p className="text-slate-500 dark:text-slate-400 text-xs sm:text-sm font-mono">
            &copy; 2025-2026 SOPHIE Daddy Quant Blog. Educational content for informational purposes only.
          </p>
        </div>
      </footer>
    </div>
  );
}

export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
  const ticker = (await params).ticker.toUpperCase();
  
  // TODO: In a real application, you might want to fetch company data here
  // For now, we'll use the enhanced metadata generation for better SEO
  return generateEnhancedStockMetadata(ticker);
}
