import { StockDetailClient } from "@/app/stock/[ticker]/stock-detail-client";
import { Header } from "@/components/layout/header";
import { Metadata } from "next";
import { generateStockMetadata, generateEnhancedStockMetadata } from "@/components/seo/stock-seo";

type Params = {
  ticker: string;
};

export default async function StockDetailPage({ params }: { params: Params }) {
  // In Next.js 15, we need to handle params as a promise
  const ticker = (await params).ticker.toUpperCase();
  
  return (
    <div className="min-h-screen flex flex-col bg-slate-50 dark:bg-slate-950">
      <Header />
      <main className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 py-6 sm:py-8 w-full">
        <StockDetailClient ticker={ticker} />
      </main>

      {/* Educational Disclaimer matching ArticleFrame */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 pb-12 w-full">
        <div className="bg-amber-50 dark:bg-amber-950/30 border-l-4 border-amber-500 p-6 rounded-r-2xl">
          <h4 className="font-bold text-amber-900 dark:text-amber-300 mb-2">Educational Disclaimer</h4>
          <p className="text-amber-800 dark:text-amber-400 text-sm">
            SOPHIE analysis is for educational purposes only, intended for people to learn more about finance, but not giving financial advice. All suggestions and valuations are generated by AI models and quantitative algorithms.
          </p>
        </div>
      </div>

      <footer className="bg-white dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 py-8 sm:py-12">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 text-center">
          <p className="text-slate-500 dark:text-slate-400 text-sm">
            &copy; 2025-2026 SOPHIE Daddy Quant Blog. Educational content for informational purposes only.
          </p>
        </div>
      </footer>
    </div>
  );
}

export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
  const ticker = (await params).ticker.toUpperCase();
  
  // TODO: In a real application, you might want to fetch company data here
  // For now, we'll use the enhanced metadata generation for better SEO
  return generateEnhancedStockMetadata(ticker);
}
