// Core-chrome-only UI strings for the EN/中文 toggle -- see src/hooks/use-language.tsx.
// Deliberately NOT covering article body content, wiki markdown, profile settings, the
// full sign-in/sign-up form (auth-dialog.tsx), forum, or tier/topic-gate messaging (out
// of scope, see the toggle's plan doc). The `auth` namespace below is a narrow exception:
// just the small "Sign in" trigger button and the Edit profile/Sign out dropdown items --
// not the auth dialog's own forms. Brand names ("SOPHIE Daddy Quant Blog", "SOPHIE",
// "YouTube", "Bilibili", "Google Docs") are never translated -- they stay as literal
// English fragments inside zh strings too.

export const en = {
  header: {
    navQuantTrending: "Quant Trending",
    navMacroClock: "Macro Clock",
    navWiki: "Wiki",
    navFeedback: "Feedback",
    navDonate: "Donate",
    admin: "Admin",
    rank: "Rank",
    theme: "Theme",
    language: "Language",
    openNavMenu: "Open navigation menu",
  },
  footer: {
    about: "About",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    feedback: "Feedback",
    copyright: "© {year} SOPHIE Daddy Quant Blog. Educational content for informational purposes only.",
  },
  disclaimer: {
    text:
      "Disclaimer: This application is a personal proof of concept created for study and research purposes only. " +
      "All analysis, suggestions, and content are generated by AI models using publicly available data and tools, " +
      "and should not be considered as financial advice. Past performance is not indicative of future results. " +
      "Always conduct your own research and consult with qualified financial professionals before making investment decisions. " +
      "The app's AI models may have limitations and may not account for all market factors or recent developments. " +
      "Users are solely responsible for their investment decisions and should understand that all investments involve risk.",
  },
  articleFrame: {
    watch: "Watch",
    enlargePlayer: "Enlarge player",
    enlargePlayerHint: "Enlarge player — keeps playing while you scroll and read",
    shrinkPlayer: "Shrink player",
    likeOnYoutube: "Like on YouTube",
    liked: "Liked",
    likedToast: "Liked! ({count} video{plural} liked so far)",
    congratsKeepItUp: "Keep it up!",
    congratsTitle: "You're now {tier}!",
    likeError: "Something went wrong.",
    bookmarkAdd: "Bookmark this article",
    bookmarkRemove: "Remove bookmark",
    playVideo: "Play video: {title}",
    previous: "Previous",
    next: "Next",
    relatedTopics: "Related Topics",
    relatedStrategies: "Related Strategies",
    researchPaper: "Research Paper",
    researchPaperDescription: "The full source paper behind this article — read it inline or open it in Google Docs.",
    readInline: "Read inline",
    openInGoogleDocs: "Open in Google Docs",
    wiki: "Wiki",
    viewFullPage: "View full page",
    viewFullWikiPage: "View full wiki page",
    close: "Close",
    wikiComingSoon: "Wiki entry coming soon for this article.",
    docNotEmbeddable: "This document isn't embeddable — open it directly in Google Docs.",
    openResearchPaper: "Open Research Paper",
    articleNotFound: "Article not found.",
    returnToHome: "Return to Home",
    optionsBadge: "Options",
    educationalDisclaimer: "Educational Disclaimer",
    universalDisclaimer:
      "This content is for educational purposes only and does not constitute financial advice. " +
      "Past performance does not guarantee future results. Always conduct your own research and " +
      "consult a qualified financial professional before making investment decisions.",
    footerCopyright: "© 2026 SOPHIE's Daddy Quant Blog. Educational content for informational purposes only.",
  },
  articleCard: {
    viewFullScreen: "View full screen",
    deepResearch: "Deep Research",
    video: "Video",
    podcast: "Podcast",
    options: "Options",
    infographic: "Infographic",
    showInfographic: "Show infographic",
    showVideoThumbnail: "Show video thumbnail",
    googleDoc: "Google Doc",
    website: "Website",
    watchOn: "Watch on {platform}",
    readArticle: "Read Article",
    bookmarkAdd: "Bookmark this article",
    bookmarkRemove: "Remove bookmark",
  },
  articleFilter: {
    searchPlaceholder: "Search articles by title or description...",
    clearAll: "Clear All",
    bookmarked: "Bookmarked",
  },
  auth: {
    signIn: "Sign in",
    editProfile: "Edit profile",
    signOut: "Sign out",
  },
  tierUpDialog: {
    nice: "Nice!",
  },
  tierUnlock: {
    topicPages: "Topic pages and real-time SPX live options data are now unlocked.",
    comments: "Comments are now unlocked.",
    premiumAndVideoPlatform: "Premium articles and your preferred video platform are now unlocked.",
    pageReview: "You've unlocked a 1:1 page review — reach out via Feedback and I'll review and help improve one of your pages.",
    customVideo: "You've unlocked a custom video — reach out via Feedback and let's set it up.",
    quantNeighborhoodPage: "You've unlocked a dedicated Quant Neighborhood page — reach out via Feedback to get it set up.",
  },
  profileSettings: {
    signInPrompt: "Sign in to edit your profile.",
    heading: "Profile settings",
    displayNameLabel: "Display name",
    avatarLabel: "Avatar",
    saving: "Saving...",
    saveChanges: "Save changes",
    profileUpdated: "Profile updated.",
    genericError: "Something went wrong.",
    updated: "Updated.",
    subscribedLabel: "I'm subscribed to the SOPHIE YouTube channel",
    subscribedDescription:
      "Promotes you to {tier} and unlocks every article automatically. We don't verify this — it's the honor system.",
    likedVideosCount:
      'Liked {count} video{plural} on YouTube — hit the "Like on YouTube" button on any article to rank up further.',
    premiumBadge: "Premium",
    preferredVideoPlatform: "Preferred video platform",
    unlocksAt: "Unlocks at {tier}",
    videoPlatformDescription:
      "When an article has both a YouTube and Bilibili version, the Watch card plays this one by default. " +
      "You can still switch per-video from the toggle on the card itself.",
    reachTierToChoose: "Reach {tier} to choose your default — see the rank-up tip above for what's next.",
    defaultOptionSource: "Default Option Chain Source",
    defaultOptionSourceDescription:
      "Choose whether the Option Chain Viewer & SPX Payoff Builder automatically load live real-time Cboe quotes by default.",
    optionSourceHistorical: "Historical Snapshot",
    optionSourceLive: "Live ^SPX (Real-Time)",
    reachTierForLiveOption: "Reach {tier} to enable Real-Time options by default.",
    defaultTopicLayout: "Default Topic Page Layout",
    defaultTopicLayoutDescription:
      "Choose whether topic guide pages default to the classic single-column layout or the two-column sidebar layout.",
    topicLayoutClassic: "Classic",
    topicLayoutSidebar: "Sidebar",
    reachTierForTopicLayout: "Reach {tier} to default to the Sidebar layout.",
    engagementHeading: "YouTube Engagement",
    premiumSettingsHeading: "Premium Settings",
    premiumSettingsDescription: "Reader preferences that unlock as your tier goes up.",
    congratsSubscribed: "Thanks for subscribing!",
    congratsAppreciate: "We really appreciate it.",
  },
  homepage: {
    tagline:
      "A personal blog and YouTube channel on quantitative finance — AI-assisted research " +
      "across market analysis, options strategies, and stock insights.",
    featurePillarQuantTitle: "Quant Finance",
    featurePillarQuantDescription: "Quantitative models and market research",
    featurePillarOptionsTitle: "Option Strategies",
    featurePillarOptionsDescription: "Options strategy research and trade ideas",
    featurePillarStockTitle: "Stock & Investment",
    featurePillarStockDescription: "AI-assisted analysis of trending stocks",
    featurePillarNeighborhoodTitle: "Quant Neighborhood",
    featurePillarNeighborhoodDescription: "Curated voices from the quant community",
    youtubeChannel: "YouTube Channel",
    podcastOnSpotify: "Podcast on Spotify",
    bilibiliChannel: "Bilibili Channel",
    xiaohongshuGroup: "Xiaohongshu Group",
    copyRssFeedUrl: "Copy RSS Feed URL",
    rssCopied: "Copied!",
    meetSophieDaddy: "Meet SOPHIE Daddy",
    interactiveArticles: "Interactive Articles",
    exploreArticlesCount: "Explore {count}+ articles on quantitative finance, options trading, and market analysis",
    featured: "Featured",
    showingArticlesCount: "Showing {shown} of {total} articles",
    showLess: "Show Less",
    showAllArticlesButton: "Show All {count} Articles",
    noArticlesFound: "No articles found matching your filters.",
    tryAdjustingFilters: "Try adjusting your search or filters.",
    aboutThePlatform: "About the Platform",
    aboutSophieHeading: "About SOPHIE",
    aboutSophieDescription:
      "SOPHIE is an open quantitative finance platform designed for students and amateurs to build systematic foundations, " +
      "and for industry practitioners like SOPHIE Daddy to discuss market news, micro/macro views, and deep-dive research. " +
      "Every topic connects in-depth articles, YouTube video walkthroughs, primary research papers, and live market tools — " +
      "and we warmly welcome your topic requests for upcoming blogs and videos.",
    aboutCardLearningTitle: "Systematic Learning",
    aboutCardLearningDescription:
      "Structured curricula, curated study paths, and foundational breakdowns help students and quant enthusiasts master financial engineering, options pricing, and factor models step by step.",
    aboutCardPractitionerTitle: "Practitioner Views & Research",
    aboutCardPractitionerDescription:
      "Wall Street practitioners like SOPHIE Daddy analyze breaking financial news, macro cycles, micro stock views, causal inference models, and cutting-edge academic papers.",
    aboutCardCommunityTitle: "Blog & YouTube Topics",
    aboutCardCommunityDescription:
      "We actively welcome research topics and strategy questions from our community to be explored in future in-depth blog articles and companion YouTube videos.",
    aboutCardOneFrameTitle: "One frame, every format",
    aboutCardOneFrameDescription:
      "Each topic pairs its article, companion video walkthrough, primary research paper, and wiki references in one seamless frame — read, watch, and learn without tab-switching.",
    aboutCardOpenTitle: "Open to everyone",
    aboutCardOpenDescription:
      "The entire article library, investment clock, and live market tools are 100% free with no sign-in required. Free sign-in unlocks bookmarking, forum discussions, and subscriber perks.",
    aboutCardToolsTitle: "Live Tools & Investment Clock",
    aboutCardToolsDescription:
      "Explore interactive macroeconomic dashboards, the live Investment Clock, quant trending trackers, and options modeling tools directly in your browser.",
    aboutSuggestTopicForum: "Suggest a Topic in Forum",
    communityAndTrendingKicker: "Community & Real-Time Pulse",
    communityAndTrendingHeading: "Discussions & Quant Trending",
    communityAndTrendingDescription:
      "Join community discussions on quantitative finance, market views, and option mechanics, and track live trending quant research from top sources.",
    latestDiscussionsTitle: "Latest Discussions",
    latestDiscussionsSubtitle: "Recent topics, article comments & feedback from members",
    viewAllDiscussions: "View Forum",
    noDiscussionsYet: "No forum discussions yet. Be the first to start a conversation!",
    quantTrendingTitle: "Quant Trending Pulse",
    quantTrendingSubtitle: "Top signals from ArXiv, GitHub, Reddit & Hacker News",
    viewAllTrending: "See All Trending",
    browseAllTopics: "Browse all topics",
    leaveFeedback: "Leave Feedback",
    exploreAllTrending: "Explore all {count} trending items",
  },
};

export const zh: typeof en = {
  header: {
    navQuantTrending: "量化热点",
    navMacroClock: "美林时钟",
    navWiki: "百科",
    navFeedback: "反馈",
    navDonate: "捐赠",
    admin: "管理员",
    rank: "等级",
    theme: "主题",
    language: "语言",
    openNavMenu: "打开导航菜单",
  },
  footer: {
    about: "关于我们",
    privacyPolicy: "隐私政策",
    termsOfService: "服务条款",
    feedback: "反馈",
    copyright: "© {year} SOPHIE Daddy Quant Blog。内容仅供教育参考，不构成任何投资建议。",
  },
  disclaimer: {
    text:
      "免责声明：本网站是仅供学习和研究使用的个人概念验证项目。所有分析、建议及内容均由 AI 模型基于公开数据和工具生成，" +
      "不构成任何投资建议。过往表现不代表未来结果。在做出投资决策前，请务必自行研究并咨询合格的金融专业人士。" +
      "本应用的 AI 模型可能存在局限性，未必能涵盖所有市场因素或最新动态。用户对自己的投资决策全权负责，并应了解所有投资均存在风险。",
  },
  articleFrame: {
    watch: "观看",
    enlargePlayer: "放大播放器",
    enlargePlayerHint: "放大播放器——滚动阅读时继续播放",
    shrinkPlayer: "缩小播放器",
    likeOnYoutube: "在YouTube点赞",
    liked: "已点赞",
    likedToast: "已点赞！（已点赞 {count} 个视频）",
    congratsKeepItUp: "继续保持！",
    congratsTitle: "你现在是{tier}了！",
    likeError: "出错了，请稍后重试。",
    bookmarkAdd: "收藏本文",
    bookmarkRemove: "取消收藏",
    playVideo: "播放视频：{title}",
    previous: "上一篇",
    next: "下一篇",
    relatedTopics: "相关主题",
    relatedStrategies: "相关策略",
    researchPaper: "研究论文",
    researchPaperDescription: "本文背后的完整原始论文——可在此内嵌阅读，或在 Google Docs 中打开。",
    readInline: "内嵌阅读",
    openInGoogleDocs: "在 Google Docs 中打开",
    wiki: "百科",
    viewFullPage: "查看完整页面",
    viewFullWikiPage: "查看完整百科页面",
    close: "关闭",
    wikiComingSoon: "本文的百科词条即将上线。",
    docNotEmbeddable: "该文档无法内嵌显示——请直接在 Google Docs 中打开。",
    openResearchPaper: "打开研究论文",
    articleNotFound: "未找到该文章。",
    returnToHome: "返回首页",
    optionsBadge: "期权",
    educationalDisclaimer: "教育性声明",
    universalDisclaimer:
      "本内容仅供教育参考，不构成任何投资建议。过往表现不能保证未来结果。" +
      "在做出投资决策前，请务必自行研究并咨询合格的金融专业人士。",
    footerCopyright: "© 2026 SOPHIE's Daddy Quant Blog。内容仅供教育参考，不构成任何投资建议。",
  },
  articleCard: {
    viewFullScreen: "全屏",
    deepResearch: "研究论文",
    video: "视频",
    podcast: "播客",
    options: "期权",
    infographic: "图解",
    showInfographic: "显示图解",
    showVideoThumbnail: "显示视频缩略图",
    googleDoc: "Google 文档",
    website: "网站",
    watchOn: "在{platform}观看",
    readArticle: "阅读全文",
    bookmarkAdd: "收藏本文",
    bookmarkRemove: "取消收藏",
  },
  articleFilter: {
    searchPlaceholder: "按标题或描述搜索文章...",
    clearAll: "清除全部",
    bookmarked: "已收藏",
  },
  auth: {
    signIn: "登录",
    editProfile: "编辑个人资料",
    signOut: "退出登录",
  },
  tierUpDialog: {
    nice: "太棒了！",
  },
  tierUnlock: {
    topicPages: "主题页面和实时SPX期权数据已解锁。",
    comments: "评论功能已解锁。",
    premiumAndVideoPlatform: "付费文章与首选视频平台已解锁。",
    pageReview: "你已解锁一对一页面点评——请通过反馈渠道联系我，我会为你评审并改进一个页面。",
    customVideo: "你已解锁定制视频——请通过反馈渠道联系我，我们一起安排。",
    quantNeighborhoodPage: "你已解锁 Quant Neighborhood 专属页面——请通过反馈渠道联系我进行设置。",
  },
  profileSettings: {
    signInPrompt: "登录后即可编辑你的个人资料。",
    heading: "个人资料设置",
    displayNameLabel: "显示名称",
    avatarLabel: "头像",
    saving: "保存中...",
    saveChanges: "保存更改",
    profileUpdated: "个人资料已更新。",
    genericError: "出错了，请稍后重试。",
    updated: "已更新。",
    subscribedLabel: "我已订阅 SOPHIE 的 YouTube 频道",
    subscribedDescription: "可晋升为{tier}并自动解锁所有文章。我们不会验证——这是诚信自律机制。",
    likedVideosCount: "已在YouTube点赞 {count} 个视频——在任意文章页点击“在YouTube点赞”按钮即可继续升级。",
    premiumBadge: "高级功能",
    preferredVideoPlatform: "首选视频平台",
    unlocksAt: "在{tier}解锁",
    videoPlatformDescription:
      "当某篇文章同时有 YouTube 和 Bilibili 版本时，观看卡片将默认播放你选择的平台。" +
      "你仍然可以在卡片上按视频单独切换。",
    reachTierToChoose: "升级到{tier}即可选择默认平台——查看上方的升级提示了解下一步。",
    defaultOptionSource: "默认期权链数据源",
    defaultOptionSourceDescription: "选择期权链查看器与 SPX 收益构建器默认是否自动加载 Cboe 实时报价。",
    optionSourceHistorical: "历史快照",
    optionSourceLive: "实时 ^SPX（真实行情）",
    reachTierForLiveOption: "升级到{tier}即可默认启用实时期权数据。",
    defaultTopicLayout: "专题页默认布局",
    defaultTopicLayoutDescription: "选择专题指南页默认使用经典单栏布局还是双栏侧边栏布局。",
    topicLayoutClassic: "经典布局",
    topicLayoutSidebar: "侧边栏布局",
    reachTierForTopicLayout: "升级到{tier}即可默认使用侧边栏布局。",
    engagementHeading: "YouTube 互动",
    premiumSettingsHeading: "高级设置",
    premiumSettingsDescription: "随等级提升逐步解锁的阅读偏好设置。",
    congratsSubscribed: "感谢你的订阅！",
    congratsAppreciate: "我们非常感激。",
  },
  homepage: {
    tagline: "关于量化金融的个人博客与 YouTube 频道——AI 辅助的市场分析、期权策略与股票洞察研究。",
    featurePillarQuantTitle: "量化金融",
    featurePillarQuantDescription: "量化模型与市场研究",
    featurePillarOptionsTitle: "期权策略",
    featurePillarOptionsDescription: "期权策略研究与交易思路",
    featurePillarStockTitle: "股票与投资",
    featurePillarStockDescription: "AI辅助的热门股票分析",
    featurePillarNeighborhoodTitle: "量化社区",
    featurePillarNeighborhoodDescription: "精选量化社区声音",
    youtubeChannel: "YouTube频道",
    podcastOnSpotify: "Spotify播客",
    bilibiliChannel: "Bilibili频道",
    xiaohongshuGroup: "小红书互动加群",
    copyRssFeedUrl: "复制RSS订阅链接",
    rssCopied: "已复制！",
    meetSophieDaddy: "认识 SOPHIE Daddy",
    interactiveArticles: "互动文章",
    exploreArticlesCount: "探索 {count}+ 篇关于量化金融、期权交易与市场分析的文章",
    featured: "精选",
    showingArticlesCount: "显示 {total} 篇文章中的 {shown} 篇",
    showLess: "收起",
    showAllArticlesButton: "显示全部 {count} 篇文章",
    noArticlesFound: "没有找到符合筛选条件的文章。",
    tryAdjustingFilters: "请尝试调整搜索词或筛选条件。",
    aboutThePlatform: "关于本平台",
    aboutSophieHeading: "关于 SOPHIE",
    aboutSophieDescription:
      "SOPHIE 是一个开放的量化金融平台，致力于帮助学生和量化爱好者进行系统化的进阶学习，" +
      "同时也为像 SOPHIE Daddy 这样的华尔街一线从业者提供交流财经新闻、宏微观市场观点与深度研究论文的阵地。" +
      "每个主题均融合了深度博客、YouTube 配套视频、原始研究论文与实用市场工具，并真诚欢迎大家提交希望在后续内容中探讨的选题。",
    aboutCardLearningTitle: "系统化学习与进阶",
    aboutCardLearningDescription:
      "精心编排的课程大纲、引导式学习路径与由浅入深的知识拆解，帮助学生与量化爱好者稳步掌握金融工程、期权定价与多因子模型等核心知识。",
    aboutCardPractitionerTitle: "从业者观点与前沿研讨",
    aboutCardPractitionerDescription:
      "像 SOPHIE Daddy 这样的华尔街一线从业者在此深入剖析实时财经新闻、宏观经济周期、微观个股研判、因果推断模型与前沿学术论文。",
    aboutCardCommunityTitle: "博客与视频选题征集",
    aboutCardCommunityDescription:
      "真诚欢迎社区读者与观众提出想深入了解的量化与投资课题，我们将在后续的深度博客文章与 YouTube 配套视频中展开专题研究与分享。",
    aboutCardOneFrameTitle: "一个界面，全部形式",
    aboutCardOneFrameDescription:
      "每个主题的文章、视频讲解、原始研究论文和百科参考资料，都在同一个可滚动界面中完整呈现——无需在多个标签页间来回切换。",
    aboutCardOpenTitle: "面向所有人免费开放",
    aboutCardOpenDescription:
      "本首页、文章库、投资时钟及实时市场工具均完全公开，无需注册即可浏览。免费登录可解锁文章收藏、学习大纲、论坛讨论与订阅特权。",
    aboutCardToolsTitle: "实时工具与宏观时钟",
    aboutCardToolsDescription:
      "体验互动式宏观经济仪表盘、实时美林投资时钟、量化热点追踪器与期权建模分析工具，浏览器内即开即用。",
    aboutSuggestTopicForum: "在论坛提交选题建议",
    communityAndTrendingKicker: "社区交流与实时脉搏",
    communityAndTrendingHeading: "社区探讨与量化热点",
    communityAndTrendingDescription:
      "参与量化金融、市场研判与期权策略的社区深度讨论，实时追踪来自全球前沿量化研究与开源动态。",
    latestDiscussionsTitle: "最新社区探讨",
    latestDiscussionsSubtitle: "来自社区成员的最新选题建议、文章评论与交流",
    viewAllDiscussions: "进入论坛",
    noDiscussionsYet: "暂无社区讨论，欢迎发表第一个话题！",
    quantTrendingTitle: "实时量化热点",
    quantTrendingSubtitle: "汇聚 ArXiv、GitHub、Reddit 及 Hacker News 实时量化动态",
    viewAllTrending: "查看全部热点",
    browseAllTopics: "浏览全部话题",
    leaveFeedback: "提交反馈",
    exploreAllTrending: "浏览全部 {count} 条量化热点",
  },
};

type Dict = typeof en;
export type TranslationKey = {
  [N in keyof Dict & string]: `${N}.${keyof Dict[N] & string}`;
}[keyof Dict & string];

function getPath(dict: Dict, key: TranslationKey): string {
  const [ns, k] = key.split(".") as [keyof Dict, string];
  return (dict[ns] as Record<string, string>)[k];
}

export function resolveTranslation(
  language: "en" | "zh",
  key: TranslationKey,
  vars?: Record<string, string | number>
): string {
  let value = language === "zh" ? getPath(zh, key) : getPath(en, key);
  if (value === undefined) {
    if (process.env.NODE_ENV !== "production") {
      console.warn(`Missing translation for key: ${key}`);
    }
    value = getPath(en, key) ?? key;
  }
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      value = value.replaceAll(`{${k}}`, String(v));
    }
  }
  return value;
}
