// Core-chrome-only UI strings for the EN/中文 toggle -- see src/hooks/use-language.tsx.
// Deliberately NOT covering article body content, wiki markdown, profile settings, the
// full sign-in/sign-up form (auth-dialog.tsx), forum, or tier/topic-gate messaging (out
// of scope, see the toggle's plan doc). The `auth` namespace below is a narrow exception:
// just the small "Sign in" trigger button and the Edit profile/Sign out dropdown items --
// not the auth dialog's own forms. Brand names ("SOPHIE Daddy Quant Blog", "SOPHIE",
// "YouTube", "Bilibili", "Google Docs") are never translated -- they stay as literal
// English fragments inside zh strings too.

export const en = {
  header: {
    navQuantTrending: "Quant Trending",
    navMacroClock: "Macro Clock",
    navWiki: "Wiki",
    navFeedback: "Feedback",
    admin: "Admin",
    rank: "Rank",
    theme: "Theme",
    language: "Language",
    openNavMenu: "Open navigation menu",
  },
  footer: {
    about: "About",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    feedback: "Feedback",
    copyright: "© {year} SOPHIE Daddy Quant Blog. Educational content for informational purposes only.",
  },
  disclaimer: {
    text:
      "Disclaimer: This application is a personal proof of concept created for study and research purposes only. " +
      "All analysis, suggestions, and content are generated by AI models using publicly available data and tools, " +
      "and should not be considered as financial advice. Past performance is not indicative of future results. " +
      "Always conduct your own research and consult with qualified financial professionals before making investment decisions. " +
      "The app's AI models may have limitations and may not account for all market factors or recent developments. " +
      "Users are solely responsible for their investment decisions and should understand that all investments involve risk.",
  },
  articleFrame: {
    watch: "Watch",
    enlargePlayer: "Enlarge player",
    enlargePlayerHint: "Enlarge player — keeps playing while you scroll and read",
    shrinkPlayer: "Shrink player",
    likeOnYoutube: "Like on YouTube",
    liked: "Liked",
    likedToast: "Liked! ({count} video{plural} liked so far)",
    congratsKeepItUp: "Keep it up!",
    congratsTitle: "You're now {tier}!",
    likeError: "Something went wrong.",
    bookmarkAdd: "Bookmark this article",
    bookmarkRemove: "Remove bookmark",
    playVideo: "Play video: {title}",
    previous: "Previous",
    next: "Next",
    relatedTopics: "Related Topics",
    relatedStrategies: "Related Strategies",
    researchPaper: "Research Paper",
    researchPaperDescription: "The full source paper behind this article — read it inline or open it in Google Docs.",
    readInline: "Read inline",
    openInGoogleDocs: "Open in Google Docs",
    wiki: "Wiki",
    viewFullPage: "View full page",
    viewFullWikiPage: "View full wiki page",
    close: "Close",
    wikiComingSoon: "Wiki entry coming soon for this article.",
    docNotEmbeddable: "This document isn't embeddable — open it directly in Google Docs.",
    openResearchPaper: "Open Research Paper",
    articleNotFound: "Article not found.",
    returnToHome: "Return to Home",
    optionsBadge: "Options",
    educationalDisclaimer: "Educational Disclaimer",
    universalDisclaimer:
      "This content is for educational purposes only and does not constitute financial advice. " +
      "Past performance does not guarantee future results. Always conduct your own research and " +
      "consult a qualified financial professional before making investment decisions.",
    footerCopyright: "© 2026 SOPHIE's Daddy Quant Blog. Educational content for informational purposes only.",
  },
  articleCard: {
    viewFullScreen: "View full screen",
    deepResearch: "Deep Research",
    video: "Video",
    podcast: "Podcast",
    options: "Options",
    infographic: "Infographic",
    showInfographic: "Show infographic",
    showVideoThumbnail: "Show video thumbnail",
    googleDoc: "Google Doc",
    website: "Website",
    watchOn: "Watch on {platform}",
    readArticle: "Read Article",
    bookmarkAdd: "Bookmark this article",
    bookmarkRemove: "Remove bookmark",
  },
  articleFilter: {
    searchPlaceholder: "Search articles by title or description...",
    clearAll: "Clear All",
    bookmarked: "Bookmarked",
  },
  auth: {
    signIn: "Sign in",
    editProfile: "Edit profile",
    signOut: "Sign out",
  },
  tierUpDialog: {
    nice: "Nice!",
  },
  tierUnlock: {
    topicPages: "Topic pages are now unlocked.",
    comments: "Comments are now unlocked.",
    premiumAndVideoPlatform: "Premium articles and your preferred video platform are now unlocked.",
  },
  profileSettings: {
    signInPrompt: "Sign in to edit your profile.",
    heading: "Profile settings",
    displayNameLabel: "Display name",
    avatarLabel: "Avatar",
    saving: "Saving...",
    saveChanges: "Save changes",
    profileUpdated: "Profile updated.",
    genericError: "Something went wrong.",
    updated: "Updated.",
    subscribedLabel: "I'm subscribed to the SOPHIE YouTube channel",
    subscribedDescription:
      "Promotes you to {tier} and unlocks every article automatically. We don't verify this — it's the honor system.",
    likedVideosCount:
      'Liked {count} video{plural} on YouTube — hit the "Like on YouTube" button on any article to rank up further.',
    premiumBadge: "Premium",
    preferredVideoPlatform: "Preferred video platform",
    unlocksAt: "Unlocks at {tier}",
    videoPlatformDescription:
      "When an article has both a YouTube and Bilibili version, the Watch card plays this one by default. " +
      "You can still switch per-video from the toggle on the card itself.",
    reachTierToChoose: "Reach {tier} to choose your default — see the rank-up tip above for what's next.",
    congratsSubscribed: "Thanks for subscribing!",
    congratsAppreciate: "We really appreciate it.",
  },
  homepage: {
    tagline:
      "A personal blog and YouTube channel on quantitative finance — AI-assisted research " +
      "across market analysis, options strategies, and stock insights.",
    featurePillarQuantTitle: "Quant Finance",
    featurePillarQuantDescription: "Quantitative models and market research",
    featurePillarOptionsTitle: "Option Strategies",
    featurePillarOptionsDescription: "Options strategy research and trade ideas",
    featurePillarStockTitle: "Stock & Investment",
    featurePillarStockDescription: "AI-assisted analysis of trending stocks",
    featurePillarNeighborhoodTitle: "Quant Neighborhood",
    featurePillarNeighborhoodDescription: "Curated voices from the quant community",
    youtubeChannel: "YouTube Channel",
    podcastOnSpotify: "Podcast on Spotify",
    bilibiliChannel: "Bilibili Channel",
    xiaohongshuGroup: "Xiaohongshu Group",
    copyRssFeedUrl: "Copy RSS Feed URL",
    rssCopied: "Copied!",
    meetSophieDaddy: "Meet SOPHIE Daddy",
    interactiveArticles: "Interactive Articles",
    exploreArticlesCount: "Explore {count}+ articles on quantitative finance, options trading, and market analysis",
    featured: "Featured",
    showingArticlesCount: "Showing {shown} of {total} articles",
    showLess: "Show Less",
    showAllArticlesButton: "Show All {count} Articles",
    noArticlesFound: "No articles found matching your filters.",
    tryAdjustingFilters: "Try adjusting your search or filters.",
    aboutThePlatform: "About the platform",
    aboutSophieHeading: "About SOPHIE",
    aboutSophieDescription:
      "SOPHIE turns scattered market research into one place worth coming back to. " +
      "Every topic pairs its article with the video, primary research paper, and wiki " +
      "reference in a single scrollable frame, backed by a live trending-topics board " +
      "and guided study paths — all free, no account required.",
    aboutCardOneFrameTitle: "One frame, every format",
    aboutCardOneFrameDescription:
      "Each topic's article, video walkthrough, primary research paper, and wiki reference " +
      "live in the same scrollable frame — read, watch, or dig into the source without " +
      "hunting across tabs.",
    aboutCardTrendingTitle: "Trending quant topics",
    aboutCardTrendingDescription:
      "A live-ranked board surfaces what's moving in quant finance and options right now, " +
      "so you always know what's actually worth reading today.",
    aboutCardStudyPathsTitle: "Guided study paths",
    aboutCardStudyPathsDescription:
      "Topic pages come with curated study guides — an ordered reading path that takes you " +
      "from first principles to fluent, instead of a random pile of articles.",
    aboutCardOpenTitle: "Open to everyone",
    aboutCardOpenDescription:
      "This home page, the article library, and the live market tools are publicly " +
      "accessible with no account and no sign-in.",
    aboutCardFreeAccountTitle: "Free account unlocks more",
    aboutCardFreeAccountDescription:
      "Signing in lets you bookmark articles, join forum discussions, open topic study " +
      "guides, and read premium articles reserved for subscribers and supporters of the channel.",
    aboutCardGooglePrivacyTitle: "Google sign-in privacy",
    aboutCardGooglePrivacyDescription:
      "Signing in with Google is one optional way to create that account. SOPHIE receives " +
      "only your name, email address, and profile picture, used solely to create your profile " +
      "and attribute your posts. SOPHIE does not access your Gmail, Drive, Calendar, or any " +
      "other Google data.",
  },
};

export const zh: typeof en = {
  header: {
    navQuantTrending: "量化热点",
    navMacroClock: "美林时钟",
    navWiki: "百科",
    navFeedback: "反馈",
    admin: "管理员",
    rank: "等级",
    theme: "主题",
    language: "语言",
    openNavMenu: "打开导航菜单",
  },
  footer: {
    about: "关于我们",
    privacyPolicy: "隐私政策",
    termsOfService: "服务条款",
    feedback: "反馈",
    copyright: "© {year} SOPHIE Daddy Quant Blog。内容仅供教育参考，不构成任何投资建议。",
  },
  disclaimer: {
    text:
      "免责声明：本网站是仅供学习和研究使用的个人概念验证项目。所有分析、建议及内容均由 AI 模型基于公开数据和工具生成，" +
      "不构成任何投资建议。过往表现不代表未来结果。在做出投资决策前，请务必自行研究并咨询合格的金融专业人士。" +
      "本应用的 AI 模型可能存在局限性，未必能涵盖所有市场因素或最新动态。用户对自己的投资决策全权负责，并应了解所有投资均存在风险。",
  },
  articleFrame: {
    watch: "观看",
    enlargePlayer: "放大播放器",
    enlargePlayerHint: "放大播放器——滚动阅读时继续播放",
    shrinkPlayer: "缩小播放器",
    likeOnYoutube: "在YouTube点赞",
    liked: "已点赞",
    likedToast: "已点赞！（已点赞 {count} 个视频）",
    congratsKeepItUp: "继续保持！",
    congratsTitle: "你现在是{tier}了！",
    likeError: "出错了，请稍后重试。",
    bookmarkAdd: "收藏本文",
    bookmarkRemove: "取消收藏",
    playVideo: "播放视频：{title}",
    previous: "上一篇",
    next: "下一篇",
    relatedTopics: "相关主题",
    relatedStrategies: "相关策略",
    researchPaper: "研究论文",
    researchPaperDescription: "本文背后的完整原始论文——可在此内嵌阅读，或在 Google Docs 中打开。",
    readInline: "内嵌阅读",
    openInGoogleDocs: "在 Google Docs 中打开",
    wiki: "百科",
    viewFullPage: "查看完整页面",
    viewFullWikiPage: "查看完整百科页面",
    close: "关闭",
    wikiComingSoon: "本文的百科词条即将上线。",
    docNotEmbeddable: "该文档无法内嵌显示——请直接在 Google Docs 中打开。",
    openResearchPaper: "打开研究论文",
    articleNotFound: "未找到该文章。",
    returnToHome: "返回首页",
    optionsBadge: "期权",
    educationalDisclaimer: "教育性声明",
    universalDisclaimer:
      "本内容仅供教育参考，不构成任何投资建议。过往表现不能保证未来结果。" +
      "在做出投资决策前，请务必自行研究并咨询合格的金融专业人士。",
    footerCopyright: "© 2026 SOPHIE's Daddy Quant Blog。内容仅供教育参考，不构成任何投资建议。",
  },
  articleCard: {
    viewFullScreen: "全屏",
    deepResearch: "研究论文",
    video: "视频",
    podcast: "播客",
    options: "期权",
    infographic: "图解",
    showInfographic: "显示图解",
    showVideoThumbnail: "显示视频缩略图",
    googleDoc: "Google 文档",
    website: "网站",
    watchOn: "在{platform}观看",
    readArticle: "阅读全文",
    bookmarkAdd: "收藏本文",
    bookmarkRemove: "取消收藏",
  },
  articleFilter: {
    searchPlaceholder: "按标题或描述搜索文章...",
    clearAll: "清除全部",
    bookmarked: "已收藏",
  },
  auth: {
    signIn: "登录",
    editProfile: "编辑个人资料",
    signOut: "退出登录",
  },
  tierUpDialog: {
    nice: "太棒了！",
  },
  tierUnlock: {
    topicPages: "主题页面已解锁。",
    comments: "评论功能已解锁。",
    premiumAndVideoPlatform: "付费文章与首选视频平台已解锁。",
  },
  profileSettings: {
    signInPrompt: "登录后即可编辑你的个人资料。",
    heading: "个人资料设置",
    displayNameLabel: "显示名称",
    avatarLabel: "头像",
    saving: "保存中...",
    saveChanges: "保存更改",
    profileUpdated: "个人资料已更新。",
    genericError: "出错了，请稍后重试。",
    updated: "已更新。",
    subscribedLabel: "我已订阅 SOPHIE 的 YouTube 频道",
    subscribedDescription: "可晋升为{tier}并自动解锁所有文章。我们不会验证——这是诚信自律机制。",
    likedVideosCount: "已在YouTube点赞 {count} 个视频——在任意文章页点击“在YouTube点赞”按钮即可继续升级。",
    premiumBadge: "高级功能",
    preferredVideoPlatform: "首选视频平台",
    unlocksAt: "在{tier}解锁",
    videoPlatformDescription:
      "当某篇文章同时有 YouTube 和 Bilibili 版本时，观看卡片将默认播放你选择的平台。" +
      "你仍然可以在卡片上按视频单独切换。",
    reachTierToChoose: "升级到{tier}即可选择默认平台——查看上方的升级提示了解下一步。",
    congratsSubscribed: "感谢你的订阅！",
    congratsAppreciate: "我们非常感激。",
  },
  homepage: {
    tagline: "关于量化金融的个人博客与 YouTube 频道——AI 辅助的市场分析、期权策略与股票洞察研究。",
    featurePillarQuantTitle: "量化金融",
    featurePillarQuantDescription: "量化模型与市场研究",
    featurePillarOptionsTitle: "期权策略",
    featurePillarOptionsDescription: "期权策略研究与交易思路",
    featurePillarStockTitle: "股票与投资",
    featurePillarStockDescription: "AI辅助的热门股票分析",
    featurePillarNeighborhoodTitle: "量化社区",
    featurePillarNeighborhoodDescription: "精选量化社区声音",
    youtubeChannel: "YouTube频道",
    podcastOnSpotify: "Spotify播客",
    bilibiliChannel: "Bilibili频道",
    xiaohongshuGroup: "小红书互动加群",
    copyRssFeedUrl: "复制RSS订阅链接",
    rssCopied: "已复制！",
    meetSophieDaddy: "认识 SOPHIE Daddy",
    interactiveArticles: "互动文章",
    exploreArticlesCount: "探索 {count}+ 篇关于量化金融、期权交易与市场分析的文章",
    featured: "精选",
    showingArticlesCount: "显示 {total} 篇文章中的 {shown} 篇",
    showLess: "收起",
    showAllArticlesButton: "显示全部 {count} 篇文章",
    noArticlesFound: "没有找到符合筛选条件的文章。",
    tryAdjustingFilters: "请尝试调整搜索词或筛选条件。",
    aboutThePlatform: "关于本平台",
    aboutSophieHeading: "关于 SOPHIE",
    aboutSophieDescription:
      "SOPHIE 把分散的市场研究整合成一个值得反复回看的地方。每个主题都将文章与视频、" +
      "原始研究论文和百科参考资料整合在同一个可滚动的界面中，并配有实时热点榜单和" +
      "引导式学习路径——完全免费，无需注册账户。",
    aboutCardOneFrameTitle: "一个界面，全部形式",
    aboutCardOneFrameDescription:
      "每个主题的文章、视频讲解、原始研究论文和百科参考资料，都在同一个可滚动界面中呈现——" +
      "阅读、观看或深入研究原始资料，无需在多个标签页间切换。",
    aboutCardTrendingTitle: "量化热点话题",
    aboutCardTrendingDescription:
      "实时排行榜展示当下量化金融与期权领域的热门动态，让你随时了解今天真正值得一读的内容。",
    aboutCardStudyPathsTitle: "引导式学习路径",
    aboutCardStudyPathsDescription:
      "主题页面配有精心编排的学习指南——按顺序排列的阅读路径，带你从基础概念逐步进阶，" +
      "而不是杂乱无章的文章堆砌。",
    aboutCardOpenTitle: "面向所有人开放",
    aboutCardOpenDescription:
      "本首页、文章库以及实时市场工具均公开可用，无需注册账户，也无需登录。",
    aboutCardFreeAccountTitle: "免费账户解锁更多内容",
    aboutCardFreeAccountDescription:
      "登录后即可收藏文章、参与论坛讨论、打开主题学习指南，并阅读专为频道订阅者与" +
      "支持者保留的付费文章。",
    aboutCardGooglePrivacyTitle: "Google 登录隐私说明",
    aboutCardGooglePrivacyDescription:
      "使用 Google 登录是创建账户的一种可选方式。SOPHIE 仅获取你的姓名、电子邮箱地址和头像，" +
      "仅用于创建你的个人资料并标注你发布的内容。SOPHIE 不会访问你的 Gmail、Drive、日历或" +
      "任何其他 Google 数据。",
  },
};

type Dict = typeof en;
export type TranslationKey = {
  [N in keyof Dict & string]: `${N}.${keyof Dict[N] & string}`;
}[keyof Dict & string];

function getPath(dict: Dict, key: TranslationKey): string {
  const [ns, k] = key.split(".") as [keyof Dict, string];
  return (dict[ns] as Record<string, string>)[k];
}

export function resolveTranslation(
  language: "en" | "zh",
  key: TranslationKey,
  vars?: Record<string, string | number>
): string {
  let value = language === "zh" ? getPath(zh, key) : getPath(en, key);
  if (value === undefined) {
    if (process.env.NODE_ENV !== "production") {
      console.warn(`Missing translation for key: ${key}`);
    }
    value = getPath(en, key) ?? key;
  }
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      value = value.replaceAll(`{${k}}`, String(v));
    }
  }
  return value;
}
