"use client"

export function Disclaimer() {
  return (
    <div className="bg-yellow-50 border-t border-yellow-200 py-4 px-4">
      <div className="container mx-auto">
        <p className="text-xs text-yellow-800 text-center">
          Disclaimer: This application is a personal proof of concept created for study and research purposes only. 
          All analysis, suggestions, and content are generated by AI models using publicly available data and tools, 
          and should not be considered as financial advice. Past performance is not indicative of future results. 
          Always conduct your own research and consult with qualified financial professionals before making investment decisions. 
          The app's AI models may have limitations and may not account for all market factors or recent developments. 
          Users are solely responsible for their investment decisions and should understand that all investments involve risk.
        </p>
      </div>
    </div>
  )
}
